// import LoginPage from "./pages/Login.jsx";
// import SignupPage from "./pages/Signup.jsx";
// import Home from "./pages/Home.jsx";
// import CreateProduct from './pages/createProduct.jsx';
// import MyProducts from "./pages/myProducts.jsx";
// import Cart from "./pages/cart.jsx";
// export { SignupPage, LoginPage, Home, CreateProduct, MyProducts, Cart, };
import LoginPage from "./Pages/Login.jsx";
import SignupPage from "./Pages/Signup.jsx";
import Home from "./Pages/Home.jsx";
import CreateProduct from './Pages/createProduct.jsx';
import MyProducts from "./Pages/myProducts.jsx";
import Cart from "./Pages/cart.jsx";
import ProductDetails from "./Pages/productDetails.jsx";
import Profile from "./Pages/profile.jsx";
import CreateAddress from "./Pages/createAddress.jsx";
import SelectAddress from "./Pages/SelectAddress.jsx";
import OrderConfirmation from "./Pages/OrderConfirmation.jsx";
import MyOrdersPage from ".Pages/myorders.jsx";
export { SignupPage, LoginPage, Home, CreateProduct, MyProducts, Cart, ProductDetails, Profile, CreateAddress,SelectAddress,OrderConfirmation,MyOrdersPage };